config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :trips

  root 'trips#index'

end

app/models/place.rb
class Place < ActiveRecord::Base

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	validates :trip_id, presence: true
	validates :address, presence: true
end

app/models/trip.rb
class Trip < ActiveRecord::Base

	has_many :places, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @trip = Trip.find_by_id(params[:trip_id])
    @place = @trip.places.build(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @trip, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
        format.js { }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:address, :latitude, :longitude, :trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @place = Place.new
    @places = @trip.places
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoadTrip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

<div class="container-fluid">
	<%= yield %>
</div>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place, remote: true ) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag "trip_id", @trip.id %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_small_form.html.erb
<%= form_for(@place, remote: true, :html => {:class => 'form-inline'} ) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag "trip_id", @trip.id %>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  
  <%= f.submit class: 'btn btn-primary' %>

<% end %>

app/views/places/create.js.erb
// Javascript template to dynamically create places

$("#place_list").append('<li><%= j @place.address %></li>');
$("#place_address").val("");

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.address %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/shared/_roadTrip.html.erb
<div class="roadtrip_render">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div class="col-xs-12 col-sm-2">
					<div class="trip_places">
						<ul id="place_list">
							<% places.each do |place| %>
								<li><%= place.address %></li>
							<% end %>
						</ul>
					</div>
				</div>

				<div class="col-xs-12 col-sm-10">

					<script>
						$( document ).ready(function() {


							handler = Gmaps.build('Google');
							handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
							
								markers = handler.addMarkers(<%=raw hash.to_json %>);

							  handler.bounds.extendWith(markers);
							  handler.fitMapToBounds();
							});

						});
					</script>

					<div style='width: 800px;'>
					  <div id="map" style='width: 800px; height: 400px;'></div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">
		  <div class="panel-body">

		  	<div class="row">
		  		<div class="col-xs-8">
		  			<%= link_to trip.title, trip %>
		  		</div>

		      <div class="col-xs-4">
		        <%= link_to 'Destroy', trip, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
		      </div>
		    </div>

		  </div>
		</div>

	</div>
</div>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <h1 style="text-align: center;">Road Trip!</h1>
  </div>
</div>



<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= link_to 'New Trip', new_trip_path, :class => "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <% @trips.each do |trip| %>
      <%= render 'trip', trip: trip %>
    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<p id="notice"><%= notice %></p>
	</div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <h1 style="text-align: center;"><%= @trip.title %></h1>
  </div>
</div>

<div class="row">
	<div class="col-xs-12">
		<h2>Add a new Place!</h2>
		<%= render "places/small_form" %>
	</div>
</div>

<div class="row">
	<div class="roadtrip_render">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-xs-12 col-sm-2">
						<div class="trip_places">
							<ul id="place_list">
								<% @places.each do |place| %>
									<li><%= place.address %></li>
								<% end %>
							</ul>
						</div>
					</div>

					<div class="col-xs-12 col-sm-10">

						<script>
							$( document ).ready(function() {


								handler = Gmaps.build('Google');
								handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
								
									markers = handler.addMarkers(<%=raw @hash.to_json %>);

								  handler.bounds.extendWith(markers);
								  handler.fitMapToBounds();
								});

							});
						</script>

						<div style='width: 800px;'>
						  <div id="map" style='width: 800px; height: 400px;'></div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<hr>

<%= link_to 'All Trips', trips_path %>